repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pdm-format
        name: pdm format
        entry: ./pre-commit/run-pdm-format.sh
        language: system
        types: [python]

      - id: pdm-test
        name: pdm test
        entry: ./pre-commit/run-pdm-test.sh
        language: system
        types: [python]
