repos:
  - repo: local
    hooks:
      - id: pre-commit-hook
        name: 🔄 - Running pre-commit hook...
        entry: ./pre-commit.sh
        language: script
        always_run: true
        files: \.(py)$
        types: [python]