repos:
  - repo: local
    hooks:
      - id: format-files
        name: 🔄 - Formatting files...
        entry: bash -c "pdm format"
        language: system
        always_run: true
        verbose: true
      - id: lint-files
        name: 🔄 - Checking files for linting errors...
        entry: bash -c "pdm lint nemli/ tests/"
        language: system
        always_run: true
        verbose: true